### ISSUE TITLE
Plymouth boot screen does not display password dots

### ISSUE THREAD

**Issue by iomintz** [grassmunk/Chicago95#28] opened 2018-01-13 09:01 UTC
## Steps to reproduce:
1. Enable dm-crypt (ryptsetup? Whatever is the default from the Ubuntu installer)
2. Install the plymouth boot screen and enable it.

## Expected behavior
Dots are displayed when you type in characters, as in the default boot screen.

## Actual behavior
No dots.

**Comment by bmintz** [comment] 2018-01-13 09:05
Looks like the issue is here:
https://github.com/grassmunk/Chicago95/blob/38b53f266d743aa4f4bce57432dc060e2cbddc45/Plymouth/Chicago95/Chicago95.script#L68

No "bullet.png" is defined. Care to provide one?

**Comment by bmintz** [comment] 2018-01-13 09:14
Would this be enough? https://orig03.deviantart.net/8752/f/2013/031/8/e/untitled_1d5_by_a7md3mad-d5td8e9.png

**Comment by EMH-Mark-I** [comment] 2018-02-02 06:41
I'll take a look at this in the following week.

**Comment by bmintz** [comment] 2018-02-10 19:36
Any progress?

**Comment by EMH-Mark-I** [comment] 2018-02-11 18:40
OK so I have it "fixed" but the dialog input is extremely slow. It was also missing a character limit for the dialog box, so if your password was very long then it would draw bullets outside the box and across the background.
I'm not very familiar with Plymouth themes so I'm going to see if I can't barrow from another theme to see if I can't fix the input latency. I'll upload it soon.

**Comment by EMH-Mark-I** [comment] 2018-02-11 19:42
Alright I put out the update. Bullets should be fixed. Input latency was being caused in the refresh_callback section at line 26 (now line 25 in the new file.) I removed the "% 18" and now typing in the password isn't a slide show, but it appears to have been necessary to loop the background progress bar animation. I don't understand what this function does, but I left it out.

**Comment by EMH-Mark-I** [comment] 2018-02-15 17:14
I'm going to close the issue soon. If you have any recommendations on looping the status bars animation without it impacting the input latency let me know! (It's no fun having to type in a 40+ disk encryption password.) For now I'm just going to leave that part out.

**Comment by EMH-Mark-I** [comment] 2018-02-16 04:30
The bullets should be there. Just in case, this would be the process of re-installing it.

1: Delete the old theme. 
$    sudo rm -rf /usr/share/plymouth/themes/Chicago95/

2: Move the updated theme into "/usr/share/plymouth/themes/"
$    sudo cp -r Plymouth/Chicago95 /usr/share/plymouth/themes/

3: sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/Chicago95/Chicago95.plymouth 100

4: sudo update-alternatives --config default.plymouth
(Select the assigned theme number. Most likely going to be 2.)

5: Update initramfs
$    sudo update-initramfs -u

**Closed** 2019-10-18 03:26 UTC
